--
-- Data domains
--
DROP DOMAIN IF EXISTS login_t CASCADE;
CREATE DOMAIN login_t AS varchar(32) NOT NULL CHECK (VALUE <> '');

DROP DOMAIN IF EXISTS lname CASCADE;
CREATE DOMAIN lname AS varchar(255) NOT NULL CHECK (VALUE <> '');

DROP DOMAIN IF EXISTS sname CASCADE;
CREATE DOMAIN sname AS varchar(24) NOT NULL CHECK (VALUE <> '');

DROP DOMAIN IF EXISTS string CASCADE;
CREATE DOMAIN string AS varchar(255);

DROP DOMAIN IF EXISTS nzstring CASCADE;
CREATE DOMAIN nzstring AS varchar(255) NOT NULL CHECK (VALUE <> '');

